# Generated by Django 5.0.7 on 2024-09-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
